### ISSUE TITLE
bug: sign in error

### ISSUE THREAD

**Issue by metasal1** [phantom/sign-in-with-solana#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1

### Current Behavior

When I click the sign in button, it displays the same error in the logs as the Sign In Error button

### Expected Behavior

Sign in 

### Steps To Reproduce

Connect wallet
Click sign in 
![IMG_0998](https://github.com/phantom/sign-in-with-solana/assets/54984459/d16a9fa9-305d-45d7-8588-25820c59a400)

**Comment by 0xproflupin** [comment]
hey, currently SIWS is only live in Phantom's 23.11.0 extension. We're bringing support for Mobile in the coming month.
